package neo.bank.contocorrente.domain.models.enums;

public enum CodiceErrore {
    

    ID_NON_PUO_ESSERE_NULL("ID_NON_PUO_ESSERE_NULL"),
    USERNAME_CLIENTE_NON_PUO_ESSERE_NULL("USERNAME_CLIENTE_NON_PUO_ESSERE_NULL"),
    CODICE_CLIENTE_NON_PUO_ESSERE_NULL("CODICE_CLIENTE_NON_PUO_ESSERE_NULL"),
    CODICE_CLIENTE_NON_PUO_ESSERE_VUOTO("CODICE_CLIENTE_NON_PUO_ESSERE_VUOTO"),
    DATA_NASCITA_CLIENTE_NON_PUO_ESSERE_VUOTA("DATA_NASCITA_CLIENTE_NON_PUO_ESSERE_VUOTA"),
    NUMERO_CONTO_NON_PUO_ESSERE_NULL("NUMERO_CONTO_NON_PUO_ESSERE_NULL"),
    CODICE_SWIFT_NON_PUO_ESSERE_NULL("CODICE_SWIFT_NON_PUO_ESSERE_NULL"),
    SOGLIA_BONIFICO_MENSILE_MINORE_UGUALE_ZERO("SOGLIA_BONIFICO_MENSILE_MINORE_UGUALE_ZERO"),
    SOGLIA_BONIFICO_GIORNALIERA_MINORE_UGUALE_ZERO("SOGLIA_BONIFICO_GIORNALIERA_MINORE_UGUALE_ZERO"),
    SOGLIE_BONIFICO_NON_VALIDE_NON_COERERENTI("SOGLIE_BONIFICO_NON_VALIDE_NON_COERERENTI"),
    CODICE_ABI_NON_PUO_ESSERE_NULL("CODICE_ABI_NON_PUO_ESSERE_NULL"),
    SOGLIA_BONIFICO_NON_PUO_ESSERE_MINORE_UGUALE_A_ZERO("SOGLIA_BONIFICO_NON_PUO_ESSERE_MINORE_UGUALE_A_ZERO"),
    CODICE_CAB_NON_PUO_ESSERE_NULL("CODICE_CAB_NON_PUO_ESSERE_NULL"),
    DATA_APERTURA_NON_PUO_ESSERE_NULL("DATA_APERTURA_NON_PUO_ESSERE_NULL"),
    DATA_CHIUSURA_NON_PUO_ESSERE_NULL("DATA_CHIUSURA_NON_PUO_ESSERE_NULL"),
    NUMERO_CARTA_NON_PUO_ESSERE_NULL("NUMERO_CARTA_NON_PUO_ESSERE_NULL"),
    IBAN_NON_PUO_ESSERE_NULL("IBAN_NON_PUO_ESSERE_NULL");

    private String codice;

    private CodiceErrore(String codice) {
        this.codice = codice;
    }

    public String getCodice() {
        return codice;
    }
    
    
}
